### ISSUE TITLE
SAOMD: 지난 스카우트 반영

### ISSUE THREAD

**Issue by item4** [item4/yui#74]
글로벌서버 한국 서비스 오픈 시점부터의 전 스카우트면 될 듯 함

**Comment by item4** [comment]
이슈에 기록되어있는 것들

* [x] 장난스런 할로윈 나이트 스카우트 #58
* [x] 달밤의 할로윈 퍼레이드 스카우트 #55
* [x] 남자들의 광연 스카우트 #53
* [x] 지나가는 시간과 우정의 기억 #52
* [x] 돌아가는 세계에 겁쳐진 검 #45
* [x] 신뢰의 증거 운명의 인연 스카우트 #37
* ~~시논 생일 기념 스카우트 #28~~
* [x] 1주년 카운트다운! 앙케이트 스카우트 #27
* [x] 폭풍에 휘날리는 해적기 스카우트 #24

**Comment by item4** [comment]
생일은 내년에 어찌 나올지 모르니 뺍시다

**Comment by item4** [comment]
## 여름밤의 축제 스카우트

### 캐릭터 4성

* [신락의 춤] 프리미어
* [여름밤에 울리는 소리] 리파
* [장사수완 좋은 노점상 리즈벳

### 무기 4성

* 천신의 폭풍검
* 풍차의 신검
* 보구의 신창

## 매력분출 여름빛 소녀 스카우트

### 캐릭터 4성

* [해바라기 여름 소녀] 시리카 
* [태양의 여름 소녀] 리즈벳 
* [장난스런 여름 소녀] 시논 
* [두근거리는 여름 처녀] 스구하
* [치유의 여름 미인] 아스나

### 4성 무기

* 비치 버스터
* 선플라워 엣지
* 마린 샷
* 아일랜드 스피어
* 릴리 망고슈

## 유카타 NIGHT 스카우트

### 캐릭터 4성

* [여름 밤을 비추는 수양버들] 아스나
* [탄도에 피는 나팔꽃] 시논
* [시원한 저녁놀의 싸리꽃] 스구하
* [노래하는 백일홍] 세븐
* [춤추듯 지는 벚꽃] 레인

### 무기 4성

* 麗刀・流れ柳(세검)
* 妖刀・雅文の調べ × 雅文の奏で(쌍검)
* 祝槍・八重の繚乱 (창)
* 宝銃・咲くや朝霧 (총)
* 霊刀・萩の露 (단검)

**Comment by item4** [comment]
## 인기 캐릭터! 강화 앙케이트 스카우트

### 캐릭터 4성

* [참영비검] 아스나
* [인연의 제미니] 유우키
* [섬광의 무도] 아스나
* [천사의 성원] 유이
* [초여름을 장식하는 처녀] 스구하

### 무기 4성

* 인과의 법칙검+1
* 엔젤 클레이모어+1
* 제미니 그라디우스+1
* 피셔즈 소드+1
* 원스 어픈 어 타임+1

**Comment by item4** [comment]
## 한여름의 트로피컬★드림 스카우트

### 캐릭터 4성

* [해변의 남국소년] 키리토
* [여름의 연인] 아스나
* [생기발랄 여름빛 소녀] 유우키
* [파도 타는 소년] 유지오
* [볼 빨간 여름의 프린세스] 앨리스

### 무기 4성

* 앵커즈 소드
* 다크 팜 소드 x 덴파레 슬라이서
* ハイビスカスカッター(단검)
* ビーチスティンガー (세검)
* シーホースセイバー (한손검)

**Comment by item4** [comment]
## 가속하는 리얼 스카우트

### 캐릭터 4성

* [일어서는 영웅] 키리토
* [맞서는 결의] 아스나
* [어그멘트 테이머] 시리카
* [이피션트 스미스] 리즈벳
* [프로그레시브 거너] 시논

### 무기 4성

* 히로익 프로미스
* 컬리지
* 에레타
* 엣지 오브 리펜트
* 어드밴서

**Comment by item4** [comment]
위에 나열한것들 모두 추가되면 이슈 종료. 나머지는 제보 받는 방식으로 진행
